server:
  port: 8080

spring:
  application:
    name: kafka-streams-mongodb
  
  # MongoDB Configuration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kafka_streams_db
      
  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    
    # Producer Configuration
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
      
    # Consumer Configuration
    consumer:
      group-id: kafka-streams-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "com.example.model"
        
    # Kafka Streams Configuration
    streams:
      application-id: kafka-streams-app
      bootstrap-servers: localhost:9092
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      properties:
        processing.guarantee: exactly_once_v2
        num.stream.threads: 2
        replication.factor: 1
        
# Kafka Topics Configuration
app:
  kafka:
    topics:
      user-events: user-events
      order-events: order-events
      processed-events: processed-events
      error-events: error-events
      dead-letter: dead-letter-topic

# Logging Configuration
logging:
  level:
    com.example: DEBUG
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"